services:
  idgrow_app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: bengak
        uid: 1000
    image: idgrow-app:latest
    container_name: idgrow_app
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=idgrow_database
      - DB_PORT=3306
      - DB_DATABASE=idgrow_db
      - DB_USERNAME=idgrowuser
      - DB_PASSWORD=idgrowpassword
    networks:
      - idgrow_network

  idgrow_webserver:
    image: nginx:latest
    container_name: idgrow_webserver
    volumes:
      - .:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - idgrow_app
    networks:
      - idgrow_network

  idgrow_database:
    image: mysql:8.0
    container_name: idgrow_database
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root_password}  # Default jika tidak ada di .env
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - idgrow_network

networks:
  idgrow_network:

volumes:
  dbdata:
